name: core_utils
description: Core utilities and services for PandoraX
version: 1.0.0+1
homepage: https://github.com/pandora/core_utils

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  injectable: ^2.3.2
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  permission_handler: ^11.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.1
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
