name: ai_llm
description: AI LLM data layer for Pandora
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  ai_core:
    path: ../ai_core
  http: ^1.1.0
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  crypto: ^3.0.3
  archive: ^3.4.0
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  # llama_cpp_dart: ^0.1.0  # Temporarily disabled due to build issues
  # tflite_flutter: ^0.9.0  # TensorFlow Lite for on-device AI - Has namespace issues
  # tflite_flutter_helper: ^0.2.1  # Helper utilities
  ffi: ^2.1.0  # Foreign Function Interface for native libraries
  path: ^1.8.3  # Path utilities
  # onnxruntime: ^1.15.0  # ONNX Runtime for on-device AI - Not available
  google_generative_ai: ^0.4.6  # Google AI for cloud-based inference
  device_info_plus: ^10.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  flutter_lints: ^5.0.0
