name: pandora
packages:
  - packages/**
  - packages/cac_core
  - packages/cac_data
  - packages/common_entities
  - packages/performance_monitoring
  - packages/mobile_optimization
  - packages/realtime_processing
  - packages/phase1_demo
  - packages/advanced_ai_models
  - packages/federated_learning
  - packages/edge_computing
  - packages/phase2_demo
  - packages/multi_cloud_support
  - packages/advanced_cloud_services
  - packages/cost_optimization
  - packages/phase3_demo
  - packages/realtime_collaboration
  - packages/advanced_federated_learning
  - packages/complete_edge_computing
  - packages/phase4_demo
  - packages/production_optimization
  - packages/security_hardening
  - packages/monitoring_alerting
  - packages/documentation_deployment
  - packages/phase5_demo

scripts:
  get:
    run: melos exec -- "flutter pub get"
    description: Get all Flutter dependencies.
  analyze:
    run: melos exec -- "flutter analyze"
    description: Analyze all packages.
  test:
    run: melos exec -- "flutter test"
    description: Run all tests.
  test:coverage:
    run: melos exec -- "flutter test --coverage"
    description: Run all tests with coverage.
  build_runner:
    run: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build_runner for code generation in all packages.
  clean:
    run: melos exec -- "flutter clean"
    description: Clean all Flutter projects.
  format:
    run: melos exec -- "dart format ."
    description: Format all Dart code.
  lint:
    run: melos exec -- "dart analyze --fatal-infos"
    description: Run linting with strict rules.
  security:
    run: melos exec -- "dart pub audit"
    description: Run security audit on all packages.
  build:android:
    run: |
      cd packages/pandora
      flutter build apk --release
    description: Build Android APK.
  build:ios:
    run: |
      cd packages/pandora
      flutter build ios --release --no-codesign
    description: Build iOS app (no code signing).
  build:web:
    run: |
      cd packages/pandora
      flutter build web --release
    description: Build web app.
  build:windows:
    run: |
      cd packages/pandora
      flutter build windows --release
    description: Build Windows app.
  build:macos:
    run: |
      cd packages/pandora
      flutter build macos --release
    description: Build macOS app.
  build:linux:
    run: |
      cd packages/pandora
      flutter build linux --release
    description: Build Linux app.
  integration:test:
    run: |
      cd packages/pandora
      flutter test integration_test/
    description: Run integration tests.
  version:patch:
    run: melos version --no-git-tag-version
    description: Bump patch version for all packages.
  version:minor:
    run: melos version minor --no-git-tag-version
    description: Bump minor version for all packages.
  version:major:
    run: melos version major --no-git-tag-version
    description: Bump major version for all packages.
  phase1:demo:
    run: |
      cd packages/phase1_demo
      flutter run
    description: Run Phase 1 demo app.
  phase1:test:
    run: |
      cd packages/performance_monitoring
      flutter test
      cd ../mobile_optimization
      flutter test
      cd ../realtime_processing
      flutter test
    description: Run Phase 1 tests.
  phase2:demo:
    run: |
      cd packages/phase2_demo
      flutter run
    description: Run Phase 2 demo app.
  phase2:test:
    run: |
      cd packages/advanced_ai_models
      flutter test
      cd ../federated_learning
      flutter test
      cd ../edge_computing
      flutter test
    description: Run Phase 2 tests.
  phase3:demo:
    run: |
      cd packages/phase3_demo
      flutter run
    description: Run Phase 3 demo app.
  phase3:test:
    run: |
      cd packages/multi_cloud_support
      flutter test
      cd ../advanced_cloud_services
      flutter test
      cd ../cost_optimization
      flutter test
    description: Run Phase 3 tests.
  phase4:demo:
    run: |
      cd packages/phase4_demo
      flutter run
    description: Run Phase 4 demo app.
  phase4:test:
    run: |
      cd packages/realtime_collaboration
      flutter test
      cd ../advanced_federated_learning
      flutter test
      cd ../complete_edge_computing
      flutter test
    description: Run Phase 4 tests.
  phase5:demo:
    run: |
      cd packages/phase5_demo
      flutter run
    description: Run Phase 5 demo app.
  phase5:test:
    run: |
      cd packages/production_optimization
      flutter test
      cd ../security_hardening
      flutter test
      cd ../monitoring_alerting
      flutter test
      cd ../documentation_deployment
      flutter test
    description: Run Phase 5 tests.