name: phase2_demo
description: Demo app for Phase 2 AI Enhancement implementation
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Phase 2 packages
  advanced_ai_models:
    path: ../advanced_ai_models
  federated_learning:
    path: ../federated_learning
  edge_computing:
    path: ../edge_computing
  
  # UI dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
