name: design_tokens
description: Design tokens and theming system for PandoraX
version: 1.0.0+1
homepage: https://github.com/pandora/design_tokens

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
