include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    unnecessary_null_comparison: error
    unnecessary_statements: error
    avoid_print: warning
    avoid_unnecessary_containers: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
