name: common_entities
description: Common entities and base classes for PandoraX
version: 1.0.0+1
homepage: https://github.com/pandora/common_entities

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
