name: federated_learning
description: Privacy-preserving federated learning system for Jarvis Workspace
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  dio: ^5.4.0
  uuid: ^4.4.0
  logger: ^2.0.2+1
  
  # Cryptography
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  
  # Local storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.1
  
  # Performance monitoring
  performance_monitoring:
    path: ../performance_monitoring
  
  # Real-time processing
  realtime_processing:
    path: ../realtime_processing
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Async processing
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
