name: phase1_demo
description: Demo app for Phase 1 implementation
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Phase 1 packages
  performance_monitoring:
    path: ../performance_monitoring
  mobile_optimization:
    path: ../mobile_optimization
  realtime_processing:
    path: ../realtime_processing
  
  # UI dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
