name: core
description: Core package for Phase 4 Architecture - shared functionality and utilities
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Logging
  logger: ^2.0.2+1
  
  # JSON
  json_annotation: ^4.8.1
  
  # Path
  path: ^1.8.3
  
  # UUID
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # JSON code generation
  json_serializable: ^6.7.1
  
  # Build runner
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
