name: advanced_ai_models
description: Advanced AI models integration for Jarvis Workspace
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  dio: ^5.4.0
  uuid: ^4.4.0
  logger: ^2.0.2+1
  
  # AI/ML dependencies
  google_generative_ai: ^0.4.6
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Model management
  path_provider: ^2.1.1
  shared_preferences: ^2.3.3
  
  # Performance monitoring
  performance_monitoring:
    path: ../performance_monitoring
  
  # Real-time processing
  realtime_processing:
    path: ../realtime_processing
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Async processing
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
