name: performance_monitoring
description: Production-ready performance monitoring system for Jarvis Workspace
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  shared_preferences: ^2.3.3
  http: ^1.1.0
  uuid: ^4.4.0
  
  # Performance monitoring
  firebase_performance: ^0.9.2+8
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  
  # Real-time monitoring
  websocket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Metrics and analytics
  prometheus_client: ^1.0.0
  
  # Logging
  logger: ^2.0.2+1
  
  # JSON handling
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
