include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    forbidden_imports: error
  rules:
    forbidden_imports:
      forbidden:
        - 'package:cac_data/**'
        - 'package:pandora/**'
        - 'package:ai_llm/**'
        - 'package:note_data/**'
        - 'package:note_domain/**'
        - 'package:pandora_ui/**'
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_super_parameters: true
