name: cac_core
description: Core entities and interfaces for Pandora CAC

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  common_entities:
    path: ../common_entities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.0
  json_serializable: ^6.7.1
