name: documentation_deployment
description: Comprehensive documentation and deployment system for Jarvis Workspace
version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  dio: ^5.4.0
  uuid: ^4.4.0
  logger: ^2.0.2+1
  
  # Documentation generation
  markdown: ^7.2.2
  yaml: ^3.1.2
  
  # All previous packages
  performance_monitoring:
    path: ../performance_monitoring
  multi_cloud_support:
    path: ../multi_cloud_support
  advanced_cloud_services:
    path: ../advanced_cloud_services
  cost_optimization:
    path: ../cost_optimization
  realtime_collaboration:
    path: ../realtime_collaboration
  advanced_federated_learning:
    path: ../advanced_federated_learning
  complete_edge_computing:
    path: ../complete_edge_computing
  production_optimization:
    path: ../production_optimization
  security_hardening:
    path: ../security_hardening
  monitoring_alerting:
    path: ../monitoring_alerting
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Async processing
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
